name: core_domain
description: Core data transfer objects for the BLE IM application.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  meta: ^1.11.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
